pysat/pysatModels

pysatModelUtils/utils/match.py

Routine previously could not handle a missing model file.  New try/except statement will allow matching to continue regardless of the exception thrown by
the user-supplied file loading module.
Addresses bug found in `pysat.mode_utils` that is fixed in https://github.com/pysat/pysat/pull/317
This has been tested by running a period of time where some model files are missing.
* OS X Sierra
* python 2.7.15

BUG: missing model file

---

.travis.yml

xarray 0.14.0 is not compatible with python 3.5.  This updates the environment setup in Travis CI to manually install both `xarray` and `pandas` (which is required by xarray and will create errors down the line if not installed manually in the environment).
Also updated the custom `pysat` install to develop since the no_sgp4 branch is merged there.
Updates to Travis CI environment, so tested there.  Based on lessons learned from sami2py/sami2py#81 and pysat/pysatMissionPlanning#7.

BUG: python 3.5 unit tests and xarray

---

.travis.yml

Pysat 2.1.0 is now available via pip.  There is no longer a need for the custom pysat install, so the pysat family of codes is being upgraded to a "standard" installation through pip.  This will allow the `no_sgp4` branch of pysat to be deleted.
- Test environment update
Updates to Travis-CI environment, so tested there.

TST: clean up pysat install on travis

---

pysatModelUtils/utils/match.py

Limit instrument downloads when matching data by checking times against the
current file list.
The biggest flaw is that it keeps checking the database for periods when there are no files.  This isn't a huge issue for satellites (CINDI has only a few 'missing' files per year), but is a big issue for ISR data.
I added this change to reduce the time of my SAMI3 model validation runs and has been run for CINDI IVM and JRO ISR for multiple year-long runs.
* Operating system: OS X Sierra
* Version number: 2.7

ENH: limit downloads

---

pysatModels/utils/extract.py
pysatModels/utils/match.py

Found a bug in `utils.extract` where a list of keys was not created correctly.
Also made some style changes and improved the model loading logic.
This has been run using multiple instruments and time periods lasting from several days to a year.
* Operating system: OS X
* Version number: 2.7 and 3.7

BUG: treatment of keys

---

.travis.yml
pysatModels/tests/test_utils_extract.py
pysatModels/utils/match.py

Addresses #22 and #24.
- Uses the new `pysat_testmodel` object in test_utils_extract to more closely simulate how the code will be used.
- Updates custom.add to custom.attach in `collect_inst_model_pairs` to match pysat 3.0.0 syntax.
- Implements netcdf fixes in travis environment documented in pysat/pysat#401 and pysat/pysat#383.  These were keeping pysat from loading.
- Breaking change (fix or feature that would cause existing functionality
to not work as expected)
Tested locally and on Travis CI using pytest.
* Mac OSX 10.15.4
* python 3.7.3

TST/BUG: Use testmodel object, update to custom.attach

---

pysatModels/tests/test_utils_match.py

Unit tests currently check for an error message if no model is supplied.  This error message should not be generated, so this test is removed.
pytest -vs
* Mac OS X 10.15.4
* python 3.7.3

TST/BUG: remove unused test for match.collect_inst_model_pairs

---

docs/requirements.txt
setup.py

Fixes bug in documentation where docstrings were not showing up on readthedocs.  Partially addresses #35.
Also fixes `setup.py`, adding PyForecastTools as a requirement and making some style fixes.
This has been tested by running the branch on readthedocs.
* Operating system: readthedocs
* Version number: 3.7.8

readthedocs requirements

---

.travis.yml
CONTRIBUTING.md
pysatModels/__init__.py
pysatModels/models/__init__.py
pysatModels/tests/test_utils_extract.py
pysatModels/tests/test_utils_match.py
pysatModels/utils/__init__.py
pysatModels/utils/compare.py
pysatModels/utils/extract.py
pysatModels/utils/match.py
setup.cfg
setup.py

Adds flake8 testing to the Travis CI tests.
Tested via Travis CI.
- W503 and W504 (line breaks and operators) are mutually exclusive.  Ignoring W503 to better match PEP8 standards.

TST: Add pytest-flake8 to travis tests

---

pysatModels/models/ucar_tiegcm.py
pysatModels/utils/extract.py

Pysat 3.0.0 will no longer carry around datetime, DataFrame, and Series objects.  Libraries should import these directly from datetime and pandas.  This had been removed in pysat/pysat#369, but needs to be fixed in the dependent libraries before it can be merged there.  Pre-emptively fixing bugs before they propagate down.  These objects have been found via global search.
Also updates `logger.warn` to `logger.warning` in response to a DeprecationWarning.
Tested locally with the `pandas_update` branch of pysat and pytest.
* Mac OS X 10.15.4
* python 3.7.3

STY/BUG: pysat 3.0 style conventions, logger DeprecationWarning

---

.travis.yml
pysatModels/models/__init__.py
pysatModels/models/ucar_tiegcm.py
pysatModels/tests/test_models.py
pytest.ini
setup.cfg

Addresses #6 (partial)
- Tests the ucar_tiegcm object with the instrument test routines from pysat.  
- Updates properties of ucar_tiegcm to be consistent with pysat 3.0.0 changes
- Breaking change (fix or feature that would cause existing functionality
to not work as expected)
pytest -vs
* Mac OS X 10.15.6
* python 3.7.3
- Tied to pysat/pysat#391 for now.  Will update to develop-3 once that is merged.
- In a general case, needs modifications for downloaded instruments.  Current code will clear `first` and `second` flags.  No downloaded models currently here.

TST: test models with inherited unit tests from pysat

---

pysatModels/tests/test_utils_extract.py
pysatModels/tests/test_utils_match.py
pysatModels/utils/extract.py
pysatModels/utils/match.py

Fixed and added more unit tests for the `extract_modelled_observations` routine in `utils.extract`.
Partially addresses #6 
Unit tests run locally `python3 -m pytest test_utils_extract.py::TestUtilsExtractModObs` from the test directory. 
* Version number: 3.7

Unit tests for extract routine `extract_modelled_observations`

---

.travis.yml

Following on from pysat/pysat#409, uses conda to manage the test env in Travis CI.  This allows the artificial caps on netCDF4 and other packages to be removed.
Also includes a round of testing for numpy 1.15 with python 3.6, which are the minimum required versions for NEP 29 compliance.
https://numpy.org/neps/nep-0029-deprecation_policy.html
Changes to Travis env, so tested there.

TST: use conda to manage travis env & NEP29

---

.travis.yml
pysatModels/tests/test_models.py

Changes to the pysat test_instrument_class are implemented in pysat/pysat#420 for improved interface with instrument libraries that have downloadable instruments.  This updates the syntax here to match the new routines.
Temporarily using the `remove_madrigal` pysat branch while in draft form.  Will update once pysat develop-3 is updated.
Tested locally via pytest with the remove_madrigal branch of pysat.
* Mac OS X 10.15.4
* python 3.7.3
* pytest 5.4.1

TST: update use of test_instrument_class

---

.travis.yml

The latest matplotlib (3.3.0rc1) requires numpy 1.16.  Since NEP 29 drops 1.15 support on July 23 and no release is planned before then, dropping this now to keep travis tests running smoothly .
Change to Travis CI configuration, so tested there.

TST: use numpy 1.16 as the minimum version

---

pysatModels/utils/match.py

The way custom function input is specified changed to use `args` and `kwargs` in `pysat` PR 433: https://github.com/pysat/pysat/pull/433
This PR looked for all implementations of `custom` and updated them.  Addresses issue #45.
This was found/tested by running `match.collect_inst_model_pairs` with longitude updating.
* Version number: 3.7.7

BUG: custom input changed

---

.coveragerc
.travis.yml
docs/supported_models.rst
pysatModels/models/__init__.py
pysatModels/models/sami2py_sami2.py
setup.cfg

Addresses #44 
Adds an instrument object for sami2py, including download support for the test data file hosted at the sami2py github page. 
```
import datetime as dt
import pysat
from pysatModels.models import sami2py_sami2
sami2 = pysat.Instrument(inst_module=sami2py_sami2, tag='test')
sami2.download(dt.datetime(2019, 1, 1), dt.datetime(2019, 1, 1))
sami2.load(2019, 1)
```

ENH: add sami2py model object

---

.github/pull_request_template.md
README.md
docs/conf.py
docs/index.rst

Following the style set up in other pulls.  Renaming default branch as `main`.  NOTE: updated the front page and template info with the creation of main, since we are still not to a release point here.  Tests on `main` failing because of changes instituted when the package changed name.
- This change is a documentation update
verifying the badges are working correctly

DOC: rename default as main in docs

---

pysatModels/models/sami2py_sami2.py
pysatModels/models/ucar_tiegcm.py
pysatModels/tests/test_utils_extract.py
pysatModels/tests/test_utils_match.py

Addresses pysat/pysat#473, test with pysat/pysat#556
Updates use of `sat_id` to `inst_id`.
Passing locally with the `break/inst_id` branch of pysat.  Expected to fail on Travis until pysat/pysat#556 is merged.
- Breaking change (fix or feature that would cause existing functionality
to not work as expected)
Try importing any instrument with the `break/inst_id` branch of pysat.  Pysat will only load the instrument if this is configured properly.
* Operating system: Mac OS X 10.15.6
* Version number: python 3.8.2

MAINT: use inst_id

---

pysatModels/models/sami2py_sami2.py
pysatModels/models/ucar_tiegcm.py
pysatModels/tests/test_models.py
pysatModels/tests/test_utils_match.py

Updates syntax for instrument tests inherited from pysat as part of pysat/pysat#552.
- End-to-end instrument tests now iterate over a list of dict objects containing info to create an instrument
- pytest.mark statements updated accordingly
- `package` renamed as `inst_loc`
- Currently failing on Travis since these updates are not in pysat develop-3, but passes locally when using the tst/inst_test_class_update branch of pysat.
- Breaking change (fix or feature that would cause existing functionality
to not work as expected)
Running unit tests locally
* Version number: Python 3.7

Inst test update

---

pysatModels/models/sami2py_sami2.py
pysatModels/models/ucar_tiegcm.py

Adds support for loading multiple filenames within `.load` methods for SAMI and TIEGCM.
Please describe the tests that you ran to verify your changes. Provide
instructions so we can reproduce. Please also list any relevant details for
your test configuration
- Tested locally by registering pysatModels.models and loading a UCAR-TIEGCM file.
* macOS Catalina 
* 10.15.4

ENH: Load multiple days

---

.github/workflows/main.yml
README.md
docs/installation.rst
pysatModels/tests/test_utils_match.py
requirements.txt

Addresses #85
- Adds `requests` to list of requirements and in documentation.
- Updates NEP29 version of numpy for testing to 1.18.  This will prevent issues with pandas in the future, since they have dropped support for 1.17.0.
- Bug fix: use num_samples=12 rather than inst_id='12'.  This may be superseded by #83, but is fixed here so tests pass.
Via Github Actions

MAINT/BUG: Update requirements, NEP29

---

.github/workflows/docs.yml
.github/workflows/main.yml
pysatModels/models/pydineof_dineof.py
pysatModels/models/sami2py_sami2.py
pysatModels/tests/test_models.py
pysat_requirements.txt

Addresses #89
Updates the new main.yml tests for windows compliance post pysat 3.0.1 release.
A file link was left open after loading files, which messed with the ability to delete the tempdir on windows systems.  Closing the file after load solves the issue.  In the long term, changes will be needed at pysat. See pysat/pysat#887

BUG: update windows bugs

---

pysatModels/utils/extract.py
pysatModels/utils/match.py

Changes necessary to perform evaluations with ICON data.  ICON revealed the following issues:
1) files may start just before the start day
2) units don't conform to `pysat.utils.scale_units` standards (e.g., 'degrees North' instead of 'degrees')
Ran a SAMI3-ICON topside ion density validation.
* Version number: 3.9
* Any details about your local setup that are relevant: full success requires changes implemented in 'add_io_utils' branch on pysat.

Icon fixes

---

docs/examples/ex_match.rst

Fixed an incorrect variable name.  Also removed extra whitespace and replaced tabs with spaces.  Added more explanation so that users won't be worried about the warnings as a command runs. Addresses #86.
Ran the examples in this file and re-created the figure.
* Operating system: OS X Big Sur
* Version number: Python 3.8
* Any details about your local setup that are relevant: develop branch of pysat

Updated match example
