setup.py

Update requirements list to let pysat handle other dependencies.

BUG: refine requirements

---

pysatModelUtils/tests/test_utils_extract.py
pysatModelUtils/tests/test_utils_match.py
pysatModelUtils/utils/extract.py
pysatModelUtils/utils/match.py

Adding unit tests.  This is in progress here, because pysat won't install on my laptop so I can't run the tests locally.
Addresses #6 
Please include a summary of the change and which issue is fixed. Please also
include relevant motivation and context. List any dependencies that are required
for this change.  Please see ``CONTRIBUTING.md`` for more guidelines.
From the test directory:
`python -m pytest test_utils_match.py`
* OS X Mojave

utils.match unit tests (In Progress)

---

CHANGELOG.md
pysatModelUtils/tests/test_utils_extract.py
pysatModelUtils/utils/extract.py

This pull starts with work performed for ICON and TIEGCM comparisons, not previously pushed, and will finish with better code.
The plan:
- Pull out translation from altitude to pressure level as independent method and validate.
- Incorporate exponential RegularGrid along z
- rename methods from satellite to instrument
- improve xarray compatibility
TBD
* Operating system
* Version number

Improving Instrument View through Model

---

pysatModelUtils/tests/test_utils_extract.py
pysatModelUtils/tests/test_utils_match.py
pysatModelUtils/utils/extract.py
pysatModelUtils/utils/match.py

Incremental improvement to unit tests
Addresses #6 
Tested by running unit tests locally.
* Version number: 2.7 :-P

More unit tests: Prep for name change

---

pysatModels/tests/test_utils_extract.py
pysatModels/utils/compare.py
pysatModels/utils/extract.py
pysatModels/utils/match.py

Provides fixes for several bugs that were found when running the model validations for individual experiments and groups of experiments over a year of data.
I tested this by running 10 sets of comparison runs between DINEOFs and Jicamarca drift data.
* Operating system: OSX Sierra
* Version number: 3.7 (gasp!)

BUG: extract, match, compare, unit tests

---

pysatModels/tests/test_utils_match.py
pysatModels/utils/extract.py
pysatModels/utils/match.py

Added more unit test for the routines in utils.match.
Partially addresses #6 
- Testing
This has been tested by running all the unit tests locally.
* Operating system: OSX Mojave
* Version number: 3.7.7

utils.match unit tests

---

.coveragerc

Includes test routines in coverage reports.
Via Travis CI

TST: include test scripts in coverage reports

---

.coveragerc
.travis.yml

Incorporate changes introduced in PR #47 to fix travis failures
Will be tested on travis.

Update custom_change base

---

pysatModels/models/sami2py_sami2.py

Addresses #52.
Provides a temporary patch until sami2py metadata can be sorted out.
loading the data for the test instrument.

BUG: Sami2py patch

---

docs/supported_models.rst

Addresses #56.
- This change is a documentation update
`make html`

DOC: updates to doc style

---

pysatModels/models/sami2py_sami2.py
pysatModels/models/ucar_tiegcm.py

Addresses #50, pysat/pysat#180, and pysat/pysat#486
- Uses new pysat dosctring style for ucar_tiegcm and sami2py models
- adds acknowledgements and references for the models
- Uses general `list_files` for ucar_tiegcm
- remove python 2 imports
- cleans up comments left over from templates
- Style fix (non-breaking change which fixes an issue)
via unit tests.
tiegcm should be tested locally, I don't have the files for this.

STY: Update model style

---

pysatModels/models/sami2py_sami2.py
pysatModels/models/ucar_tiegcm.py

Update model Instrument logger handles and simplify pysat imports.
Tested by initializing one of the instruments and seeing the logger info message.
* Version number: python 3.7
- [N/A] Add a note to ``CHANGELOG.md``, summarizing the changes

STY: update logger handle

---

.travis.yml
pysatModels/models/sami2py_sami2.py
pysatModels/models/ucar_tiegcm.py
pysatModels/tests/test_utils_extract.py
pysatModels/tests/test_utils_match.py
pysatModels/utils/extract.py
pysatModels/utils/match.py
requirements.txt
test_requirements.txt

Updated the load docstrings so that variable names in the docs reflect those in the code.
Fixed in response to https://github.com/pysat/pysat/pull/587, which did not require any local updates.
No code changed.

DOC: updated load docstrings

---

pysatModels/utils/match.py

Updated custom format to use new attachment format and also remove old 'modify' kind specification.
Addresses changes incorporated in pysat PR: https://github.com/pysat/pysat/pull/654
Running match unit tests with desired pysat branch.
* Version number: Python 3.7
* Any details about your local setup that are relevant: pysat at https://github.com/pysat/pysat/pull/654
- [N/A] Add a note to ``CHANGELOG.md``, summarizing the changes

STY: updated custom format

---

pysatModels/tests/test_models.py

Updates to latest pysat standard in https://github.com/pysat/pysat/pull/637
Unit tests pass locally
* MacOS
* Python 3.8

ENH: Update to latest pysat.params['data_dirs'] standard

---

pysatModels/models/pydineof_dineof.py

Updates location of test pydineof file to most recent GitHub repo.
TravisCI

BUG: Updated test file URL

---

CONTRIBUTING.md
README.md
docs/conf.py
docs/examples.rst
docs/examples/ex_init.rst
docs/examples/ex_match.rst
docs/supported_models.rst
pysatModels/utils/extract.py
pysatModels/utils/match.py

Added examples for the utils.match routines and added the readthedocs badge to the README. 
Partially addresses #35.
- Documentation update
This has been tested by running `make html` from the `pysatModels/pysatModels/docs` directory of my computer.  I was then able to read the documentation and follow all the hot links.  The code examples are based off of code I use, but have not been tested in full because I don't have a TIEGCM file.
* Version number: python 3.7.7

Documentation for utils.match routines

---

pysatModels/tests/test_utils_compare.py
pysatModels/utils/compare.py

Added unit tests for the `compare` utility routines. Partially addresses #6 
Running the unit tests locally and outside of the test structure.
* Version number: 3.9
* Any details about your local setup that are relevant: pysat develop branch
- [N/A] Add a note to ``CHANGELOG.md``, summarizing the changes

Comparison unit tests

---

pysatModels/models/pydineof_dineof.py

Pulls in bug fixes found in #82 
- Unit tests
* Operating system: MacOS
* Version number: Python 3.8

Pydineof download changes

---

.github/pull_request_template.md
.github/workflows/main.yml
.zenodo.json
README.md
requirements.txt
setup.cfg

Updates documentation and testing in preparation for the RC.
Linted json

Doc update

---

docs/utils.rst
pysatModels/__init__.py
pysatModels/models/__init__.py
pysatModels/models/methods/__init__.py
pysatModels/models/methods/general.py
pysatModels/models/pydineof_dineof.py
pysatModels/models/sami2py_sami2.py
pysatModels/models/ucar_tiegcm.py
pysatModels/tests/test_methods_general.py

Addresses #90 by extracting common download code from the model instruments.  Also extracts common cleaning code and fixes problems with docstrings.
Added new unit tests
* Operating system: OS X Big Sur
* Version number: python 3.9
* Any details about your local setup that are relevant: develop branch of pysat

ENH: Created general model methods

---

pysatModels/tests/test_utils_compare.py
pysatModels/utils/compare.py
pysatModels/utils/extract.py
pysatModels/utils/match.py

When running the local JRO ISR model validation scripts, several errors were encountered.  This pull request fixes these bugs.  I believe these were introduced by changes in xarray.
Ran local scripts, ran unit tests
* Operating system: OS X big sur
* Version number: 3.8, 3.9
* Any details about your local setup that are relevant: coord_bugfix branch of pysat

BUG: bugs when running JRO ISR validaiton

---

README.md
docs/requirements.txt

Corrects badgelinks in readme. Corrects `m2r` to `m2r2` to get RTD to build.
Please describe the tests that you ran to verify your changes. Provide
instructions so we can reproduce. Please also list any relevant details for
your test configuration
- Local test of readme badge
- Local test showed RTD was not working. Works now. https://pysatmodels.readthedocs.io/en/readme_tweaks/
* Operating system: MacOS
* Version number: Python 3.9

Readme tweaks

---

pysatModels/models/pydineof_dineof.py
pysatModels/models/sami2py_sami2.py
pysatModels/models/ucar_tiegcm.py

Cleaned up formatting for model Instruments by:
- cleaning up the docstrings,
- cleaning up function kwarg defaults, and
- streamlining init method attribute definitions.
Addresses https://github.com/orgs/pysat/projects/4/views/1
- Style update
Testing on CI, python is broken locally.
* Operating system: GitHub Actions
* Version number
- [ N/A] Make sure you are merging into the ``develop`` (not ``main``) branch

STY: improved Instrument formatting

---

CONTRIBUTING.md
docs/overview.rst
pysatModels/models/sami2py_sami2.py
pysatModels/tests/test_methods_general.py
pysatModels/tests/test_models.py

Updates windows tests following style elsewhere.  
Fixes tabs for formatting in contributing doc.
Github Actions!

BUG: windows testing
